NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=["GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6","GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ"]
SIGNING_KEY="GCQLPBWOQ5PAJYEEQBE7GDSY7X3LCYKFEBKOCNF3OUA6F74ORK74HVSQ"
WEB_AUTH_ENDPOINT="https://anchor.ngnc.online/auth"
TRANSFER_SERVER_SEP0024="https://anchor.ngnc.online/sep24"

[DOCUMENTATION]
ORG_NAME="LINK.IO LTD."
ORG_DBA="LINK"
ORG_URL="https://www.linkio.africa"
ORG_LOGO="https://uploads-ssl.webflow.com/60a70a1080cf2974d4b1595e/60b623a4d06b3b67a49c9e82_WEBCLIP.png"
ORG_DESCRIPTION="LINK is building web3 Cross Border payments infrastructure for the next billion Africans, providing services in a Faster and Cheaper way"
ORG_PHYSICAL_ADDRESS="2 Fredrick Street, Kings Cross, London, United Kingdom WC1X 0ND"
ORG_OFFICIAL_EMAIL="support@linkio.africa"
ORG_TWITTER="link_io"
ORG_GITHUB="linkioafrica"
ORG_SUPPORT_EMAIL="support@linkio.africa"

[[PRINCIPALS]]
name="Evarist Emmanuel"
email="evaristec@linkio.africa"

[[PRINCIPALS]]
name="Tomisin Leshi"
email="tomisinleshi@linkio.africa"

[[CURRENCIES]]
code = "USDC",
issuer = "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
name = "USDC Coin",
desc = "Asset backed token pegged 1:1 to US Dollar",
display_decimals = 2,
is_asset_anchored= "true",
is_unlimited= "true",
anchor_asset_type= "fiat",
anchor_asset= "USD",
redemption_instructions= "contact Authorized Dealers or signup with KYC info on LINK",
status= "test",
image= "https://uploads-ssl.webflow.com/60a70a1080cf2974d4b1595e/61961ce43c530394bcb05349_USDC.png"
